---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflzapp
  namespace: netflzapp
  labels:
    app: netflzapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflzapp
  template:
    metadata:
      labels:
        app: netflzapp
    spec:
      containers:
        - name: netflzapp
          image: iscanprint/netflzapp:3.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflzapp
  namespace: netflzapp
  labels:
    app: netflzapp
spec:
  type: LoadBalancer   #NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: netflzapp
